name: Build Adapt

on:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4.0.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup build cache
        uses: actions/cache@v3.3.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Gradle Permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --full-stacktrace

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Adapt
          path: build/libs
